---
version: 2
default: &defaults
  working_directory: /home/circleci/lsp
  machine:
    image: circleci/classic:edge
workflows:
  version: 2
  checkout_build_help_test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - help:
          requires:
            - checkout
      - test:
          requires:
            - build
            - help
      - build-arm64:
          requires:
            - checkout
      - help-arm64:
          requires:
            - checkout
      - test-arm64:
          requires:
            - build-arm64
            - help-arm64
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root:  .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make amd64
  help:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make help-amd64
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test-amd64
  build-arm64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Qemu packages for the cross compilation
          # https://www.ecliptik.com/Cross-Building-and-Running-Multi-Arch-Docker-Images/
          command: |
            sudo apt update;
            sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
      - run: make arm64
  help-arm64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Qemu packages for the cross compilation
          # https://www.ecliptik.com/Cross-Building-and-Running-Multi-Arch-Docker-Images/
          command: |
            sudo apt update;
            sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
      - run: make help-arm64
  test-arm64:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Qemu packages for the cross compilation
          # https://www.ecliptik.com/Cross-Building-and-Running-Multi-Arch-Docker-Images/
          command: |
            sudo apt update;
            sudo apt install -y qemu qemu-user-static qemu-user binfmt-support
      # No go binary on the user mode Qemu for arm.
      # https://github.com/golang/go/issues/13024#issuecomment-164894790
      - run: make c-test-arm64
