---
version: 2
default: &defaults
  working_directory: /home/circleci/project/lsp
  docker:
    - image: gcc:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - run:
          requires:
            - checkout
      - test:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci/project/lsp
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/project/lsp
      - run: make
  run:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/project/lsp
      - run: make run
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/project/lsp
      - run: make test
