---
version: 2
default: &defaults
  working_directory: /home/circleci/project/lsp
  docker:
    - image: gcc:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      # https://research.swtch.com/vgo-tour
      - checkout
      - persist_to_workspace:
          # https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
          root: /home/circleci/project/lsp
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/project/lsp
      - run: make
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/project/lsp
      - run: make test
