---
version: 2
default: &defaults
  working_directory: /home/circleci/project/lsp
  docker:
    - image: gcc:latest
workflows:
  version: 2
  build_clean:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - help:
          requires:
            - checkout
      - test:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install libsystemd
          command: |
            apt update
            apt install -y libsystemd-dev
      - persist_to_workspace:
          root: /
          paths:
            - etc
            - usr/include/systemd
            - usr/x86_64-linux-gnu
            - home/circleci/project/lsp
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make
  help:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make help
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run: make test
